theme = "reveal-hugo"

baseURL = 'https://airdb.dev/ppt'

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[logo]
src = "airdb-logo.svg"
alt = "" # Alt text. 
width = "15%" # Size of the file.
diag = "1%" # How far from the top right should the file be.
top = "1%" # Overrides diag.
right = "1%" # Overrides diag.

[params.logo]
src = "airdb-logo.svg"
